baseURL: https://vinsouza.work/
languageCode: en-us
title: Vin Souza (@tryvin)
theme: webflow
params:
    home:
        aboutme: Hey! My name is Vin, and I'm a Senior Software Developer with extensive experience in high concurrency systems on the web, databases of all sizer. Jack-of-all-trades. Addicted to problem solving.
        skills:
            1frontend:
                content:
                    css:
                        name: CSS & CSS3
                        percentage: 90
                    javascript:
                        name: JavaScript
                        percentage: 100
                    html:
                        name: HTML & HTML 5
                        percentage: 87
                    react:
                        name: React & React Native
                        percentage: 89
                    ionic:
                        name: Ionic
                        percentage: 80
                    phonegap:
                        name: Phonegap
                        percentage: 100
            2backend:
                color: blue
                coding: coding
                content:
                    php:
                        name: PHP (Pure, Laravel, CodeIgniter and Symfony)
                        percentage: 100
                    python:
                        name: Python
                        percentage: 89
                    nodejs:
                        name: Node.JS (Firebase, Express.JS, Electron Apps)
                        percentage: 80
                    android:
                        name: Java & Kotlin for Android
                        percentage: 87
                    ios:
                        name: Objective-C and Swift for iOS
                        percentage: 83
                    sql:
                        name: SQL with Query Optimization
                        percentage: 100
                    caching:
                        name: Caching and Search systems (Redis, ElasticSearch, MongoDB)
                        percentage: 93
            3management:
                color: red
                coding: assets
                content:
                    aws:
                        name: AWS Stack
                        percentage: 89
                    devops:
                        name: DevOPS with C/I, C/D
                        percentage: 89
                    sysadmin:
                        name: Servers Administration & Automation
                        percentage: 97
                    scrum:
                        name: Scrum & Scrum Master
                        percentage: 99
                    accountancy:
                        name: USA and Brazilian Accountancy
                        percentage: 78
                    ux:
                        name: U/X and U/I (Improving my skills every day)
                        percentage: 78
    footer:
        text: 2018 Vin Souza
        social:
            networks:
                linkedin:
                    link: https://linkedin.com/in/tryvin
                    title: LinkedIN
                    icon: linkedin
